FROM alpine:3.19.0

WORKDIR /

RUN apk --no-cache add \
wget \
curl \
tar \
make \
git \    
ncurses \
curl \
llvm17 \
python3 \
py3-pip \
gcc-arm-none-eabi \
cmake \
rpm \
openssh \
sed \

RUN git config --global core.autocrlf input
